# All other configurations are set by default. If you want to add new config options,
# please modify ../connectomics/config/defaults.py
SYSTEM:
  NUM_GPUS: 2
  NUM_CPUS: 8
AUGMENTOR:
  SMOOTH: False
MODEL:
  INPUT_SIZE: [17, 257, 257]
  OUTPUT_SIZE: [17, 257, 257]
  IN_PLANES: 1
  OUT_PLANES: 3
  TARGET_OPT: ["2"]
  LABEL_EROSION: 1
  LOSS_OPTION: [["WeightedBCEWithLogitsLoss", "DiceLoss"]]
  LOSS_WEIGHT: [[1.0, 0.5]]
  WEIGHT_OPT: [["1", "0"]]
  OUTPUT_ACT: [["none", "sigmoid"]]
  FILTERS: [32, 64, 96, 128, 160]
  NORM_MODE: gn
DATASET:
  INPUT_PATH: datasets/AC3-AC4/   # or your own dataset path
  IMAGE_NAME: AC4_train_inputs.h5
  LABEL_NAME: AC4_train_labels.h5
  VAL_IMAGE_NAME: AC4_val_inputs.h5
  VAL_LABEL_NAME: AC4_val_labels.h5
  OUTPUT_PATH: outputs/AC3-AC4/res_unet
  PAD_SIZE: [4, 64, 64]
SOLVER:
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.02
  ITERATION_STEP: 1
  ITERATION_SAVE: 10000
  ITERATION_TOTAL: 150000
  SAMPLES_PER_BATCH: 2
MONITOR:
  ITERATION_NUM: [200, 1000]
INFERENCE:
  INPUT_SIZE: [17, 513, 513]
  OUTPUT_SIZE: [17, 513, 513]
  OUTPUT_ACT: ["sigmoid"]
  IMAGE_NAME: AC3_inputs.h5
  OUTPUT_PATH: outputs/AC3-AC4/test
  OUTPUT_NAME: result.h5
  PAD_SIZE: [4, 32, 32]
  AUG_MODE: min
  AUG_NUM: None
  STRIDE: [8, 128, 128]
  SAMPLES_PER_BATCH: 4
MONITOR:
  LOG_OPT: [1, 1, 1]
